data_collection_paths:
  data_sources_json: "artifacts/data/data_sources/agri_data_sources.json"
  collected_data_dir: "artifacts/data/collected_data"
  arxiv_dir: "artifacts/data/collected_data/arxiv"
  core_json_files:
    - "artifacts/data/data_sources/core_data_1748674199.json"
    - "artifacts/data/data_sources/core_data_1748675418.json"

LOG_PATH: "logs"
SOURCE_DATA_PATH: "artifacts/data/collected_data/"
SOURCE_DIRS: ["arxiv", "pdfs", "core"]
DATA_PATH: "artifacts/data/grouped_data/"
GROUPED_DIRS: ["group_6", "group_7"]

CHROMA_DB_PATH: "chromadb"

CHUNKS_OUT_PATH_FAISS: "artifacts/model_inferences/faiss/chunks.jsonl"
FAISS_DB_PATH: "faiss"

QUERY_TEXT: "What depths were used for monitoring soil suction using the miniature tensiometer at the Boissy-le-Châtel site?"
EVALUATION_DATA_PATHS: "artifacts/data/evaluation_data/questions.json"
RESULTS_CSV_PATH: "artifacts/results/evaluation_results.csv"

CHUNK_SIZE: 512
CHUNK_OVERLAP: 50
CHUNK_LOWER_LIMIT: 100
CHUNK_UPPER_LIMIT: 500
BATCH_SIZE: 64
INGEST_BATCH_SIZE: 64
K: 10
R: 5
N: 3
MAX_N: 4

ENCODING_MODEL: "cl100k_base"
# EMBEDDING_MODEL: "BAAI/bge-small-en"
EMBEDDING_MODEL: "intfloat/multilingual-e5-large-instruct"
RE_RANK_MODEL: "cross-encoder/ms-marco-MiniLM-L-6-v2"
# LOCAL_LLM: "qwen3:0.6b"
LOCAL_LLM: "llama3.2"